[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11,<3.12"
dependencies = [
    "fastapi",
    "pillow",
    "python-multipart",
    "ultralytics",
    "uvicorn",
    "opencv-python-headless",
]
