services:
  - type: web
    name: thermal-analyzer-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --timeout 300 --workers 1 --threads 2 --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.7.17
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
    plan: free
    healthCheckPath: /
    autoDeploy: true

  - type: static
    name: thermal-analyzer-frontend
    buildCommand: cd FrontEnd && npm install && npm run build
    staticPublishPath: ./FrontEnd/dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://thermal-analyzer-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    plan: free
    autoDeploy: true

