services:
  - type: web
    name: thermal-analyzer-backend
    runtime: python
    buildCommand: uv sync
    startCommand: uv run uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
    plan: free
    healthCheckPath: /
    autoDeploy: true

  - type: static_site
    name: thermal-analyzer-frontend
    buildCommand: cd FrontEnd && npm install && npm run build
    staticPublishPath: ./FrontEnd/dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://thermal-analyzer-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    plan: free
    autoDeploy: true

